const express = require('express');
const path = require('node:path');
const fs = require('node:fs');
require('dotenv').config();
const multer = require('multer');
const XLSX = require('xlsx');
const admin = require('firebase-admin');

const app = express();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 15 * 1024 * 1024 } });
const port = process.env.PORT || 3000;
function initFirebase() { if (admin.apps.length) return admin.app(); const credentials = process.env.FIREBASE_SERVICE_ACCOUNT_JSON; const credentialsPath = process.env.FIREBASE_SERVICE_ACCOUNT_PATH; if (credentialsPath) return admin.initializeApp({ credential: admin.credential.cert(JSON.parse(fs.readFileSync(path.resolve(credentialsPath), 'utf8'))) }); if (!credentials) throw new Error('FIREBASE_SERVICE_ACCOUNT_PATH or FIREBASE_SERVICE_ACCOUNT_JSON is missing'); return admin.initializeApp({ credential: admin.credential.cert(JSON.parse(credentials)) }); }
function db() { initFirebase(); return admin.firestore(); }
function now() { return admin.firestore.Timestamp.now(); }
function clean(data) { return JSON.parse(JSON.stringify(data, (_, value) => value?.toDate ? value.toDate().toISOString() : value)); }
async function auth(req, res, next) { try { initFirebase(); const token = req.headers.authorization?.replace('Bearer ', ''); if (!token) return res.status(401).json({ error: 'Authentication required' }); req.user = await admin.auth().verifyIdToken(token); const profile = await db().collection('users').doc(req.user.uid).get(); if (!profile.exists || profile.data().active === false) return res.status(403).json({ error: 'Account is inactive' }); req.profile = { id: req.user.uid, ...profile.data() }; next(); } catch { res.status(401).json({ error: 'Invalid authentication token' }); } }
function adminOnly(req, res, next) { if (req.profile.role !== 'ADMIN') return res.status(403).json({ error: 'Admin access required' }); next(); }
function scopedQuery(req) { let query = db().collection('leads'); if (req.profile.role !== 'ADMIN') query = query.where('assignedTo', '==', req.profile.employeeId); return query; }
function normalizeImportRow(row) { const values = Object.fromEntries(Object.entries(row).map(([key, value]) => [key.toLowerCase().replaceAll('_', ' ').trim(), String(value ?? '').trim()])); const pick = (...keys) => keys.map((key) => values[key]).find(Boolean) || ''; return { companyName: pick('company name', 'company', 'organization'), clientName: pick('client name', 'client'), contactPerson: pick('contact person', 'contact', 'contact name'), phone: pick('phone', 'mobile', 'mobile number', 'phone number'), alternatePhone: pick('alternate phone', 'alternate number'), email: pick('email', 'email address'), address: pick('address'), city: pick('city'), state: pick('state'), website: pick('website'), industry: pick('industry'), leadSource: pick('lead source', 'source'), requirement: pick('requirement', 'requirement type'), length: pick('length'), breadth: pick('breadth'), width: pick('width'), height: pick('height'), floors: pick('floors'), coveredArea: pick('covered area', 'coveredarea'), plotArea: pick('plot area', 'plotarea'), notes: pick('notes', 'remarks') }; }
app.use(express.json({ limit: '2mb' }));
app.get('/api/health', (_, res) => res.json({ ok: true, service: 'axis-fire-crm' }));
// This deliberately exposes only active employee display names/usernames for the
// employee selector. Passwords, IDs and any lead data remain protected by auth.
app.get('/api/login-employees', async (_, res) => { try { const result = await db().collection('users').where('role', '==', 'EMPLOYEE').get(); res.json({ employees: clean(result.docs.filter((item) => item.data().active !== false).map((item) => ({ name: item.data().name, username: item.data().username }))).sort((a, b) => a.name.localeCompare(b.name)) }); } catch (error) { res.status(503).json({ error: 'Employee sign-in is temporarily unavailable' }); } });
app.use('/api', auth);
app.get('/api/me', (req, res) => res.json({ user: clean(req.profile) }));
app.get('/api/dashboard', async (req, res) => { const leads = (await scopedQuery(req).get()).docs.map((item) => ({ id: item.id, ...item.data() })); const statuses = ['New', 'Contacted', 'Follow-up Required', 'Interested', 'Quotation Required', 'Site Visit Required', 'Converted', 'Not Interested', 'Not Reachable', 'Wrong Number', 'Call Back Later', 'Lost']; const stats = Object.fromEntries(statuses.map((status) => [status, leads.filter((lead) => lead.status === status).length])); res.json({ total: leads.length, stats, leads: clean(leads), followUpsToday: leads.filter((lead) => lead.nextFollowUp === new Date().toISOString().slice(0, 10)).length }); });
app.get('/api/team-activity', adminOnly, async (req, res) => { const today = new Date().toISOString().slice(0, 10); const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10); const [users, leadsResult, auditResult] = await Promise.all([db().collection('users').where('role', '==', 'EMPLOYEE').get(), db().collection('leads').get(), db().collection('audit').orderBy('createdAt', 'desc').limit(500).get()]); const leads = leadsResult.docs.map(item => ({ id: item.id, ...item.data() })); const audit = auditResult.docs.map(item => ({ id: item.id, ...item.data() })); const employees = users.docs.filter(item => item.data().active !== false).map(item => { const employee = item.data(); const assigned = leads.filter(lead => lead.assignedTo === item.id); const completedToday = audit.filter(event => event.actorId === item.id && String(event.createdAt?.toDate ? event.createdAt.toDate().toISOString() : event.createdAt || '').startsWith(today)).length; const scheduledToday = assigned.filter(lead => lead.nextFollowUp === today).length; return { id: item.id, name: employee.name, username: employee.username, assigned: assigned.length, scheduledToday, completedToday, remainingToday: Math.max(0, scheduledToday - completedToday), scheduledTomorrow: assigned.filter(lead => lead.nextFollowUp === tomorrow).length, overdue: assigned.filter(lead => lead.nextFollowUp && lead.nextFollowUp < today).length }; }); res.json({ date: today, tomorrow, employees, recent: clean(audit.slice(0, 20)) }); });app.get('/api/leads', async (req, res) => { let leads = (await scopedQuery(req).get()).docs.map((item) => ({ id: item.id, ...item.data() })); const q = String(req.query.q || '').toLowerCase().trim(); if (q) leads = leads.filter((lead) => [lead.companyName, lead.clientName, lead.contactPerson, lead.phone, lead.email, lead.city, lead.requirement].some((value) => String(value || '').toLowerCase().includes(q))); for (const key of ['status', 'assignedTo', 'batchId', 'priority']) if (req.query[key]) leads = leads.filter((lead) => lead[key] === req.query[key]); leads.sort((a, b) => String(b.lastUpdated || '').localeCompare(String(a.lastUpdated || ''))); const total = leads.length; const page = Math.max(1, Number(req.query.page) || 1); const limit = Math.min(100, Math.max(10, Number(req.query.limit) || 25)); res.json({ leads: clean(leads.slice((page - 1) * limit, page * limit)), total, page, limit, pages: Math.max(1, Math.ceil(total / limit)) }); });
app.get('/api/leads/:id', async (req, res) => { const ref = db().collection('leads').doc(req.params.id); const snapshot = await ref.get(); if (!snapshot.exists || (req.profile.role !== 'ADMIN' && snapshot.data().assignedTo !== req.profile.employeeId)) return res.status(404).json({ error: 'Lead not found' }); const activity = await ref.collection('activity').orderBy('createdAt', 'desc').get(); res.json({ lead: clean({ id: snapshot.id, ...snapshot.data() }), activities: clean(activity.docs.map((item) => ({ id: item.id, ...item.data() }))) }); });
app.patch('/api/leads/:id', async (req, res) => { const ref = db().collection('leads').doc(req.params.id); const snapshot = await ref.get(); if (!snapshot.exists || (req.profile.role !== 'ADMIN' && snapshot.data().assignedTo !== req.profile.employeeId)) return res.status(404).json({ error: 'Lead not found' }); const allowed = ['status', 'requirement', 'priority', 'nextFollowUp', 'employeeNotes', 'adminNotes', 'length', 'breadth', 'width', 'height', 'floors', 'coveredArea', 'plotArea', 'convertedRequirement', 'estimatedDealValue', 'actualDealValue', 'conversionDate']; const changes = Object.fromEntries(Object.entries(req.body).filter(([key, value]) => allowed.includes(key) && value !== undefined && (req.profile.role === 'ADMIN' || key !== 'adminNotes'))); if (!Object.keys(changes).length) return res.status(400).json({ error: 'No valid changes supplied' }); if (changes.status === 'Converted' && !changes.conversionDate) changes.conversionDate = new Date().toISOString().slice(0, 10); changes.lastUpdated = now(); const changedFields = Object.keys(changes).filter((key) => key !== 'lastUpdated'); const batch = db().batch(); batch.update(ref, changes); batch.set(ref.collection('activity').doc(), { actorId: req.user.uid, actorName: req.profile.name, text: changes.status === 'Converted' ? 'Marked this lead as Converted' : `Updated ${changedFields.join(', ')}`, changes: changedFields, createdAt: now() }); batch.set(db().collection('audit').doc(), { actorId: req.user.uid, actorName: req.profile.name, action: changes.status === 'Converted' ? 'Lead converted' : 'Lead updated', recordId: ref.id, createdAt: now() }); await batch.commit(); res.json({ ok: true }); });
app.get('/api/batches', async (req, res) => { let query = db().collection('batches').where('archived', '==', false); if (req.profile.role !== 'ADMIN') query = query.where('assignedTo', '==', req.profile.employeeId); const result = await query.get(); const employeeIds = [...new Set(result.docs.map((item) => item.data().assignedTo).filter(Boolean))]; const profiles = await Promise.all(employeeIds.map((id) => db().collection('users').doc(id).get())); const names = Object.fromEntries(profiles.filter((item) => item.exists).map((item) => [item.id, item.data().name])); res.json({ batches: clean(result.docs.map((item) => ({ id: item.id, ...item.data(), employeeName: names[item.data().assignedTo] || 'Unassigned' }))) }); });
app.get('/api/batches/:id', async (req, res) => { const batch = await db().collection('batches').doc(req.params.id).get(); if (!batch.exists || (req.profile.role !== 'ADMIN' && batch.data().assignedTo !== req.profile.employeeId)) return res.status(404).json({ error: 'Batch not found' }); const leads = await db().collection('leads').where('batchId', '==', batch.id).get(); const employee = batch.data().assignedTo ? await db().collection('users').doc(batch.data().assignedTo).get() : null; res.json({ batch: clean({ id: batch.id, ...batch.data(), employeeName: employee?.exists ? employee.data().name : 'Unassigned' }), leads: clean(leads.docs.map(item => ({ id: item.id, ...item.data() }))) }); });
app.get('/api/batches/:id/export.xlsx', async (req, res) => { const batch = await db().collection('batches').doc(req.params.id).get(); if (!batch.exists || (req.profile.role !== 'ADMIN' && batch.data().assignedTo !== req.profile.employeeId)) return res.status(404).json({ error: 'Batch not found' }); const leads = (await db().collection('leads').where('batchId', '==', batch.id).get()).docs.map(item => item.data()); const rows = leads.map(lead => ({ Company: lead.companyName || '', Client: lead.clientName || '', Contact: lead.contactPerson || '', Phone: lead.phone || '', Email: lead.email || '', Address: lead.address || '', City: lead.city || '', State: lead.state || '', Requirement: lead.requirement || '', Length: lead.length || '', Breadth: lead.breadth || '', Width: lead.width || '', Height: lead.height || '', Floors: lead.floors || '', 'Covered area': lead.coveredArea || '', 'Plot area': lead.plotArea || '', Status: lead.status || '', Priority: lead.priority || '', 'Next follow-up': lead.nextFollowUp || '', Notes: lead.employeeNotes || lead.notes || '' })); const sheet = XLSX.utils.json_to_sheet(rows); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, sheet, 'Leads'); const buffer = XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' }); res.attachment(`${String(batch.data().name || 'batch').replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.xlsx`).type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').send(buffer); });
app.post('/api/batches', adminOnly, async (req, res) => { const name = String(req.body.name || '').trim(); const rawLeads = Array.isArray(req.body.leads) ? req.body.leads : []; if (!name) return res.status(400).json({ error: 'Batch name is required' }); if (!rawLeads.length) return res.status(400).json({ error: 'At least one valid lead is required' }); if (rawLeads.length > 450) return res.status(400).json({ error: 'Import a maximum of 450 leads per batch' }); const batchRef = db().collection('batches').doc(); const batch = { name, assignedTo: req.body.assignedTo || '', archived: false, createdAt: now(), totalLeads: rawLeads.length }; const batchWrite = db().batch(); batchWrite.set(batchRef, batch); for (const rawLead of rawLeads) { const { invalid, duplicate, ...lead } = rawLead; batchWrite.set(db().collection('leads').doc(), { ...lead, batchId: batchRef.id, assignedTo: batch.assignedTo, status: lead.status || 'New', priority: lead.priority || 'Normal', createdAt: now(), lastUpdated: now() }); } batchWrite.set(db().collection('audit').doc(), { actorId: req.user.uid, actorName: req.profile.name, action: 'Batch created', recordId: batchRef.id, createdAt: now() }); await batchWrite.commit(); res.status(201).json({ id: batchRef.id, imported: rawLeads.length }); });
app.patch('/api/batches/:id', adminOnly, async (req, res) => { const ref = db().collection('batches').doc(req.params.id); const current = await ref.get(); if (!current.exists) return res.status(404).json({ error: 'Batch not found' }); const allowed = ['name', 'assignedTo', 'archived']; const changes = Object.fromEntries(Object.entries(req.body).filter(([key]) => allowed.includes(key))); if (!Object.keys(changes).length) return res.status(400).json({ error: 'No valid changes supplied' }); changes.lastUpdated = now(); if (changes.assignedTo !== undefined) changes.assignedAt = now(); const batchWrite = db().batch(); batchWrite.update(ref, changes); if (changes.assignedTo !== undefined) { const leads = await db().collection('leads').where('batchId', '==', ref.id).get(); if (leads.size > 450) return res.status(400).json({ error: 'This batch is too large for one reassignment. Please contact support.' }); leads.docs.forEach((lead) => batchWrite.update(lead.ref, { assignedTo: changes.assignedTo, lastUpdated: now() })); } batchWrite.set(db().collection('audit').doc(), { actorId: req.user.uid, actorName: req.profile.name, action: changes.archived ? 'Batch archived' : changes.assignedTo !== undefined ? 'Batch assigned or reassigned' : 'Batch updated', recordId: ref.id, createdAt: now() }); await batchWrite.commit(); res.json({ ok: true }); });
app.delete('/api/batches/:id', adminOnly, async (req, res) => { const ref = db().collection('batches').doc(req.params.id); const current = await ref.get(); if (!current.exists) return res.status(404).json({ error: 'Batch not found' }); const leads = await db().collection('leads').where('batchId', '==', ref.id).get(); if (leads.size > 450) return res.status(400).json({ error: 'This batch is too large to delete in one operation.' }); const batchWrite = db().batch(); leads.docs.forEach(lead => batchWrite.delete(lead.ref)); batchWrite.delete(ref); batchWrite.set(db().collection('audit').doc(), { actorId: req.user.uid, actorName: req.profile.name, action: 'Batch deleted', recordId: ref.id, createdAt: now() }); await batchWrite.commit(); res.json({ ok: true }); });
app.get('/api/employees', adminOnly, async (req, res) => { const result = await db().collection('users').where('role', '==', 'EMPLOYEE').get(); res.json({ employees: clean(result.docs.map((item) => ({ id: item.id, ...item.data() }))) }); });
app.post('/api/employees', adminOnly, async (req, res) => { const { name, username, password } = req.body; if (!name || !username || !password) return res.status(400).json({ error: 'Name, username and password are required' }); const email = `${username}@axisfire.local`; try { const user = await admin.auth().createUser({ email, password, displayName: name }); await db().collection('users').doc(user.uid).set({ name, username, role: 'EMPLOYEE', employeeId: user.uid, active: true, createdAt: now() }); await db().collection('audit').add({ actorId: req.user.uid, actorName: req.profile.name, action: 'Employee created', recordId: user.uid, createdAt: now() }); res.status(201).json({ id: user.uid, name, username, active: true }); } catch (error) { res.status(409).json({ error: error.code === 'auth/email-already-exists' ? 'Username already exists' : error.message }); } });
app.patch('/api/employees/:id', adminOnly, async (req, res) => { const ref = db().collection('users').doc(req.params.id); const snapshot = await ref.get(); if (!snapshot.exists || snapshot.data().role !== 'EMPLOYEE') return res.status(404).json({ error: 'Employee not found' }); const changes = {}; const authChanges = {}; if (req.body.name !== undefined) { const name = String(req.body.name).trim(); if (!name) return res.status(400).json({ error: 'Name cannot be empty' }); changes.name = name; authChanges.displayName = name; } if (req.body.username !== undefined) { const username = String(req.body.username).trim().toLowerCase(); if (!/^[a-z0-9._-]+$/.test(username)) return res.status(400).json({ error: 'Username contains invalid characters' }); changes.username = username; authChanges.email = `${username}@axisfire.local`; } if (req.body.active !== undefined) changes.active = Boolean(req.body.active); if (req.body.password) { if (String(req.body.password).length < 6) return res.status(400).json({ error: 'Password must contain at least 6 characters' }); authChanges.password = req.body.password; } try { if (Object.keys(authChanges).length) await admin.auth().updateUser(req.params.id, authChanges); if (Object.keys(changes).length) await ref.update(changes); } catch (error) { return res.status(409).json({ error: error.code === 'auth/email-already-exists' ? 'Username already exists' : error.message }); } await db().collection('audit').add({ actorId: req.user.uid, actorName: req.profile.name, action: req.body.active === false ? 'Employee deactivated' : req.body.password ? 'Employee password reset' : 'Employee updated', recordId: req.params.id, createdAt: now() }); res.json({ ok: true }); });
app.delete('/api/employees/:id', adminOnly, async (req, res) => { if (req.params.id === req.user.uid) return res.status(400).json({ error: 'You cannot delete your own admin account' }); const ref = db().collection('users').doc(req.params.id); const current = await ref.get(); if (!current.exists || current.data().role !== 'EMPLOYEE') return res.status(404).json({ error: 'Employee not found' }); const leads = await db().collection('leads').where('assignedTo', '==', req.params.id).get(); if (leads.size > 450) return res.status(400).json({ error: 'Reassign this employee\'s leads before deleting the account.' }); const batch = db().batch(); leads.docs.forEach(lead => batch.update(lead.ref, { assignedTo: '', lastUpdated: now() })); batch.set(db().collection('audit').doc(), { actorId: req.user.uid, actorName: req.profile.name, action: 'Employee deleted', recordId: req.params.id, createdAt: now() }); batch.delete(ref); await batch.commit(); await admin.auth().deleteUser(req.params.id); res.json({ ok: true, releasedLeads: leads.size }); });
app.get('/api/activity', async (req, res) => { let query = db().collection('audit').orderBy('createdAt', 'desc').limit(50); if (req.profile.role !== 'ADMIN') query = db().collection('audit').where('actorId', '==', req.user.uid).orderBy('createdAt', 'desc').limit(50); const result = await query.get(); res.json({ activity: clean(result.docs.map((item) => ({ id: item.id, ...item.data() }))) }); });
app.get('/api/converted', async (req, res) => { let leads = (await scopedQuery(req).where('status', '==', 'Converted').get()).docs.map((item) => ({ id: item.id, ...item.data() })); if (req.query.assignedTo) leads = leads.filter((lead) => lead.assignedTo === req.query.assignedTo); if (req.query.requirement) leads = leads.filter((lead) => lead.convertedRequirement === req.query.requirement || lead.requirement === req.query.requirement); res.json({ leads: clean(leads) }); });
app.get('/api/followups', async (req, res) => { const leads = (await scopedQuery(req).get()).docs.map((item) => ({ id: item.id, ...item.data() })).filter((lead) => lead.nextFollowUp); const today = new Date().toISOString().slice(0, 10); res.json({ today: clean(leads.filter((lead) => lead.nextFollowUp === today)), overdue: clean(leads.filter((lead) => lead.nextFollowUp < today)), upcoming: clean(leads.filter((lead) => lead.nextFollowUp > today)) }); });
app.get('/api/reports', adminOnly, async (req, res) => { const leads = (await db().collection('leads').get()).docs.map((item) => item.data()); const group = (key) => Object.entries(leads.reduce((result, lead) => { const value = lead[key] || 'Unassigned'; result[value] = (result[value] || 0) + 1; return result; }, {})).map(([label, count]) => ({ label, count })); res.json({ total: leads.length, byStatus: group('status'), byEmployee: group('assignedTo'), byRequirement: group('requirement'), converted: leads.filter((lead) => lead.status === 'Converted').length }); });
app.post('/api/import', adminOnly, upload.single('file'), async (req, res) => { if (!req.file) return res.status(400).json({ error: 'File is required' }); const workbook = XLSX.read(req.file.buffer, { type: 'buffer' }); const rows = XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]], { defval: '' }).map(normalizeImportRow); if (!rows.length) return res.status(400).json({ error: 'The file has no usable data rows' }); const existing = (await db().collection('leads').get()).docs.map((item) => item.data()); const known = new Set(existing.flatMap((lead) => [lead.phone, lead.email].filter(Boolean))); const seen = new Set(); const annotated = rows.map((row) => { const key = row.phone || row.email; const invalid = !row.companyName || !row.phone; const duplicate = Boolean(key && (known.has(key) || seen.has(key))); if (key) seen.add(key); return { ...row, invalid, duplicate }; }); const invalid = annotated.filter((row) => row.invalid).length; const duplicates = annotated.filter((row) => row.duplicate && !row.invalid).length; res.json({ rows: annotated, total: rows.length, duplicates, invalid, valid: rows.length - invalid - duplicates }); });
app.get('/api/import-template', adminOnly, (_, res) => { const columns = ['Company Name', 'Client Name', 'Contact Person', 'Phone', 'Alternate Phone', 'Email', 'Address', 'City', 'State', 'Website', 'Industry', 'Lead Source', 'Requirement', 'Notes']; res.attachment('axis-fire-import-template.csv').type('text/csv').send(`${columns.join(',')}\n`); });
app.get('/api/export', adminOnly, async (req, res) => { const leads = (await db().collection('leads').get()).docs.map((item) => item.data()); const columns = ['companyName', 'clientName', 'contactPerson', 'phone', 'email', 'city', 'state', 'assignedTo', 'batchId', 'status', 'requirement', 'priority', 'nextFollowUp', 'actualDealValue']; const csv = [columns.join(','), ...leads.map((lead) => columns.map((key) => `"${String(lead[key] ?? '').replaceAll('"', '""')}"`).join(','))].join('\n'); res.attachment('axis-fire-leads.csv').type('text/csv').send(csv); });
if (process.env.NODE_ENV === 'production') { app.use(express.static(path.join(__dirname, 'dist'))); app.get('*', (_, res) => res.sendFile(path.join(__dirname, 'dist', 'index.html'))); }
if (require.main === module) app.listen(port, () => console.log(`Axis Fire API listening on http://localhost:${port}`));
module.exports = app;
